depromeet/street-drop-server

- build.gradle
Resolve : https://github.com/depromeet/street-drop-server/issues/5
- And add Spring boot starter web
> ⚙️ config: Set to java 19 version

- build.gradle
- src/main/java/com/depromeet/streetdrop/global/config/SwaggerConfig.java
resolve : https://github.com/depromeet/street-drop-server/issues/1
- add Swagger setup
- Swagger API Document Endpoint `/swagger-ui/index.html`
> :sparkles: feat : add swagger setup

- .github/workflows/jacoco.yml
- build.gradle
- codecov.yml
- src/main/java/com/depromeet/streetdrop/HealthController.java
- src/test/java/com/depromeet/streetdrop/HealthControllerTest.java
- src/test/java/com/depromeet/streetdrop/StreetDropApplicationTests.java
Resolve : https://github.com/depromeet/street-drop-server/issues/2
> ✨ feat : add jacoco and ci setup

- README.md
resolve : https://github.com/depromeet/street-drop-server/issues/9
> :memo: docs : add ci badge and codecov badge to readme

- src/main/java/com/depromeet/streetdrop/domain/common/BaseTimeEntity.java
- src/main/java/com/depromeet/streetdrop/domain/common/dto/PageResponseDto.java
- src/main/java/com/depromeet/streetdrop/domain/common/dto/ResponseDto.java
- src/main/java/com/depromeet/streetdrop/global/common/presentation/HealthController.java
Related: #16 
- BaseTimeEntity, ResponseDto, PageResponseDto setting
> :sparkles: [feature] BaseTimeEntity, ResponseDto, PageResponseDto setting #16

- build.gradle
- src/main/java/com/depromeet/streetdrop/domains/common/BaseTimeEntity.java
- src/main/java/com/depromeet/streetdrop/domains/common/dto/PageResponseDto.java
- src/main/java/com/depromeet/streetdrop/domains/common/dto/ResponseDto.java
- src/main/java/com/depromeet/streetdrop/domains/item/entity/Item.java
- src/main/java/com/depromeet/streetdrop/domains/itemLocation/entity/ItemLocation.java
- src/main/java/com/depromeet/streetdrop/domains/music/album/entity/Album.java
- src/main/java/com/depromeet/streetdrop/domains/music/album/entity/AlbumCover.java
- src/main/java/com/depromeet/streetdrop/domains/music/artist/entity/Artist.java
- src/main/java/com/depromeet/streetdrop/domains/music/song/entity/Song.java
- src/main/java/com/depromeet/streetdrop/domains/user/entity/User.java
- src/main/java/com/depromeet/streetdrop/global/common/controller/HealthController.java
- src/main/java/com/depromeet/streetdrop/global/common/controller/SwaggerController.java
- src/test/java/com/depromeet/streetdrop/HealthControllerTest.java
패키지명 변경 및 Item, ItemLocation, Song, Aritist, Album, AlbumCover 엔티티 클래스를 추가하였습니다.
수정이나 검토가 필요한 부분 피드백 부탁드립니다.
> :sparkles: Add Entity Class

- src/main/java/com/depromeet/streetdrop/domains/music/genre/entity/Genre.java
- src/main/java/com/depromeet/streetdrop/domains/music/genre/entity/SongGenre.java
- src/main/java/com/depromeet/streetdrop/domains/music/song/entity/Song.java
Resolve : https://github.com/depromeet/street-drop-server/issues/28
> ✨feat: add genre entity

- src/main/java/com/depromeet/streetdrop/global/config/SwaggerConfig.java
Resolve : https://github.com/depromeet/street-drop-server/issues/41
> :bug: fix : add server url setup to swagger

- src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
- src/main/java/com/depromeet/streetdrop/domains/item/dto/request/ItemRequestDto.java
- src/main/java/com/depromeet/streetdrop/domains/itemLocation/dto/request/LocationRequestDto.java
- src/main/java/com/depromeet/streetdrop/domains/itemLocation/service/ItemLocationService.java
- src/main/java/com/depromeet/streetdrop/domains/music/dto/request/MusicRequestDto.java
- Null Check, 위도, 경도 Valiation 못하는 문제 해결
- lat, lon으로 인하여 조회불가능하던 문제 해결
> :bug: fix: add validation check

- src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
- src/main/java/com/depromeet/streetdrop/domains/item/entity/Item.java
- src/main/java/com/depromeet/streetdrop/domains/item/service/ItemService.java
- src/main/java/com/depromeet/streetdrop/domains/user/entity/User.java
- src/main/java/com/depromeet/streetdrop/global/security/config/WebSecurityConfig.java
- src/test/java/com/depromeet/streetdrop/global/security/provider/SecurityUserDetailsTest.java
Resolve : https://github.com/depromeet/street-drop-server/issues/59
- 드랍시 idfv값 체크 추가
> ✨  feat: add idfv check to drop item

- README.md
Resolve : https://github.com/depromeet/street-drop-server/issues/66
> :memo: document: add readme

- backend/streetdrop-api/src/test/java/unit/apis/item/controller/ItemControllerTest.java
- backend/streetdrop-core/src/main/java/com/depromeet/domains/item/dto/request/ItemRequestDto.java
- backend/streetdrop-core/src/main/java/com/depromeet/domains/item/entity/Item.java
> :bug: fix: change to non-nullable content when posting item

- backend/streetdrop-core/build.gradle
- backend/streetdrop-core/src/main/java/com/depromeet/common/error/GlobalExceptionHandler.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/error/handler/ErrorEvent.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/error/handler/ErrorEventHandler.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/monitoring/MonitoringProvider.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/monitoring/SlackMonitoringProvider.java
- backend/streetdrop-core/src/main/java/com/depromeet/infra/slack/SlackService.java
resolve : https://github.com/depromeet/street-drop-server/issues/90
> ✨ Feat : add internal server error slack alert

- backend/streetdrop-api/src/main/java/com/depromeet/apis/item/controller/ItemController.java
- backend/streetdrop-api/src/test/java/unit/apis/area/village/controller/VillageItemControllerTest.java
- backend/streetdrop-api/src/test/java/unit/apis/item/controller/ItemControllerTest.java
- backend/streetdrop-core/src/main/java/com/depromeet/domains/item/dao/ItemPointDao.java
- backend/streetdrop-core/src/main/java/com/depromeet/domains/item/dto/request/NearItemPointRequestDto.java
- backend/streetdrop-core/src/main/java/com/depromeet/domains/item/dto/response/PoiResponseDto.java
- backend/streetdrop-core/src/main/java/com/depromeet/domains/item/repository/ItemLocationRepository.java
- backend/streetdrop-core/src/main/java/com/depromeet/domains/item/service/ItemService.java
- backend/streetdrop-core/src/test/java/unit/domains/area/village/service/VillageItemServiceTest.java
- backend/streetdrop-core/src/test/java/unit/domains/item/service/ItemServiceTest.java
> :sparkles: Feat : add Inner Distance to Item poi controller

- backend/streetdrop-api/src/main/java/com/depromeet/apis/common/controller/HealthController.java
- backend/streetdrop-api/src/main/java/com/depromeet/apis/common/controller/SwaggerController.java
- backend/streetdrop-api/src/test/java/unit/apis/common/controller/HealthControllerTest.java
resolve : https://github.com/depromeet/street-drop-server/issues/88
> :recycle: Refactor : change directory common.controller to apis

- backend/streetdrop-api/src/main/resources/application.yml
- backend/streetdrop-api/src/main/resources/logback-spring.xml
- backend/streetdrop-core/src/main/java/com/depromeet/common/logging/dto/HttpRequestLogInfo.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/logging/dto/HttpResponseLogInfo.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/logging/filter/HttpLoggingFilter.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/logging/filter/wrapper/RequestWrapper.java
- backend/streetdrop-core/src/main/java/com/depromeet/common/logging/filter/wrapper/ResponseWrapper.java
Resolve : https://github.com/depromeet/street-drop-server/issues/101
- Add All Http Logging
> :sparkles: Feat : add Logging

- backend/streetdrop-api/src/test/java/unit/area/village/controller/VillageItemControllerTest.java
> :bug: fix: resolve VillageItemControllerTest fail

- backend/settings.gradle
- backend/streetdrop-notification/build.gradle
- backend/streetdrop-notification/src/main/java/com/depromeet/StreetDropNotificationApplication.java
- backend/streetdrop-notification/src/test/java/com/depromeet/StreetDropNotificationApplicationTest.java
> :sparkles: feat: Add street-drop-notification module

- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemLocationRepository.java
> :ambulance: hotfix: fix query in ItemLocationRepository

- backend/streetdrop-admin/build.gradle
> :ambulance: hotfix: add build.gradle to streetdrop-admin module

- backend/streetdrop-api/src/main/java/com/depromeet/domains/village/repository/VillageAreaRepository.java
> :bug: fix: Fix villageAreaRepository JPQL Query

- backend/streetdrop-api/src/main/java/com/depromeet/domains/geo/controller/GeoController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/geo/dto/request/ReverseGeocodeRequestDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/geo/dto/response/ReverseGeocodeResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/geo/service/GeoService.java
resolve : https://github.com/depromeet/street-drop-server/issues/129
> :sparkles: feat: add reverse geocoding api

- backend/streetdrop-api/src/main/resources/application-prod.yml
> :bug: fix: change ddl-auto validate to update

- backend/streetdrop-admin/streetdrop-admin-server/build.gradle
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/common/HealthController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/controller/UserController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/dto/ResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/dto/UserAllResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/repository/UserRepository.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/service/UserService.java
- backend/streetdrop-admin/streetdrop-admin-web/src/App.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/layout/common/Menu.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/user/UserListPage.js
- backend/streetdrop-admin/streetdrop-admin-web/src/setupProxy.js
> :sparkles: feat: find All Admin Users

- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/dto/response/UserResponseDto.java
Reslove : https://github.com/depromeet/street-drop-server/issues/143
> :sparkles: feat: add userId to user info

- .github/workflows/reviewer.yml
Resolve : https://github.com/depromeet/street-drop-server/issues/150
> ⚙️ config: auto add reviewers

- backend/streetdrop-api/src/test/java/unit/item/controller/ItemControllerTest.java
Resolve : https://github.com/depromeet/street-drop-server/issues/143
> :bug: fix: userInfoDto change test fix

- backend/streetdrop-search/build.gradle
- backend/streetdrop-search/src/main/resources/application.yml
Resolve : https://github.com/depromeet/street-drop-server/issues/154
> :gear: config: add prometheus and logging to search server

- backend/streetdrop-api/src/main/java/com/depromeet/common/error/dto/ErrorCode.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
- backend/streetdrop-api/src/main/java/com/depromeet/security/config/WebSecurityConfig.java
- backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> :sparkles: feat: add nickname change api

- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/controller/UserController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/dto/UserCountResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/repository/UserRepository.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/user/service/UserService.java
- backend/streetdrop-admin/streetdrop-admin-web/src/components/dashboard/UserLineGraph.js
- backend/streetdrop-admin/streetdrop-admin-web/src/pages/Dashboard.js
> :sparkles: feat: add admin user count by join date

- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/dto/response/UserResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
- backend/streetdrop-api/src/main/java/com/depromeet/security/config/WebSecurityConfig.java
- backend/streetdrop-api/src/test/java/unit/user/service/UserServiceTest.java
- backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
- backend/streetdrop-domain/src/main/java/com/depromeet/user/vo/MusicApp.java
> :sparkles: feat: add music app change api

- backend/streetdrop-api/build.gradle
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemLocationRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/external/querydsl/mysql/spatial/MySqlSpatialFunction.java
- backend/streetdrop-domain/build.gradle
- backend/streetdrop-domain/src/main/java/com/depromeet/common/config/QuerydslConfig.java
resolve : https://github.com/depromeet/street-drop-server/issues/145
> :recycle: refactor: ItemPoi refactor to QueryDsl

- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
- backend/streetdrop-api/src/test/java/unit/security/provider/SecurityUserDetailsTest.java
- backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
- backend/streetdrop-domain/src/main/java/com/depromeet/user/vo/MusicApp.java
> :bug: fix: return value of user.getMusicApp() is null

- backend/streetdrop-api/src/main/java/com/depromeet/security/config/WebSecurityConfig.java
> :recycle: refactor: binding POST request urls related to item in WebSecurityConfig

- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/item/controller/ItemController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/item/controller/ItemService.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/item/dto/ItemAllResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/item/dto/ItemResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/apis/item/repository/ItemRepository.java
- backend/streetdrop-admin/streetdrop-admin-web/src/App.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/layout/common/Menu.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/music/items/ItemListPage.js
Resolve : https://github.com/depromeet/street-drop-server/issues/207
> :sparkles: feat(admin): add all items view and delete item

- backend/streetdrop-api/src/main/java/com/depromeet/common/dto/InfiniteScrollMetaResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/common/dto/InfiniteScrollResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/controller/ItemController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dto/response/ItemDetailResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dto/response/ItemGroupByDateResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dto/response/ItemGroupResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemLikeRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemService.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/dto/response/MusicResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/service/MusicService.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/song/repository/SongRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserItemController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/dto/response/UserProfileResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserItemService.java
- backend/streetdrop-api/src/main/java/com/depromeet/security/config/WebSecurityConfig.java
- backend/streetdrop-common/src/main/java/com/depromeet/util/WeekUtil.java
Resolve : https://github.com/depromeet/street-drop-server/issues/215
Response Example
``` json
{
"data": [
{
"date": "2주 전",
"value": {
"itemId": 6,
"user": {
"userId": 1,
"nickname": "강한 갑오징어",
"profileImage": "https://s3.orbi.kr/data/file/united/35546557a06831597f6e7851cb6c86e9.jpg",
"musicApp": "youtubemusic"
},
"location": {
"address": "서울시 강남구 강남동"
},
"music": {
"title": "하입보이",
"artist": "New jeans",
"albumImage": "https://www.youtube.com/watch?v=YGieI3KoeZk",
"genre": [
"string"
]
},
"content": "바보",
"createdAt": "2023-06-29 19:48:36",
"itemLikeCount": 0
}
},
{
"date": "2주 전",
"value": {
"itemId": 5,
"user": {
"userId": 1,
"nickname": "강한 갑오징어",
"profileImage": "https://s3.orbi.kr/data/file/united/35546557a06831597f6e7851cb6c86e9.jpg",
"musicApp": "youtubemusic"
},
"location": { …
```
> :sparkles: feat(api): add mypage api

- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/album/repository/AlbumRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserBlockController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/repository/BlockUserRepository.java
> :recycle: refactor(api): add @Param, @Value Annotation

- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/album/repository/AlbumRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/repository/BlockUserRepository.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/234
> :bug: hotfix(api): api import hotfix

- backend/streetdrop-notification/src/main/java/com/depromeet/repository/UserDeviceRepository.java
- backend/streetdrop-notification/src/main/java/com/depromeet/service/PushService.java
- backend/streetdrop-notification/src/main/java/com/depromeet/service/TopicService.java
> 🚑 hotfix(notification): find tokens using findDeviceTokenByUserId -> findByUserId

- backend/streetdrop-notification/src/main/java/com/depromeet/repository/UserDeviceRepository.java
- backend/streetdrop-notification/src/main/java/com/depromeet/service/PushService.java
> 🚑 hotfix: find tokens of all users using findAllDeviceTokens -> findAll

- .github/workflows/api-deploy.yml
- .github/workflows/jacoco.yml
- Resolve : https://github.com/depromeet/street-drop-server/issues/232
> :wrench: config(ci): change ci by dir

- backend/streetdrop-api/src/main/java/com/depromeet/external/swagger/config/SwaggerConfig.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/249
> :bug: fix(api): add swagger profile

- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dto/response/ItemGroupByDateResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserItemService.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/247
- IOS 팀 요청으로 수정
> :bug: fix(api): modify user item query response

- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemLikeRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserItemService.java
- backend/streetdrop-common/src/main/java/com/depromeet/util/WeekUtil.java
> :ambulance: hotfix(api): hotfix sorting by date

- README.md
> :memo: docs: git readme update

- .github/workflows/docusaurus.yml
-  fix github action docusaurus.yml
> :bug: fix(docs): fix github action docusaurus.yml

- docs/docusaurus.config.js
> :bug: fix(docs): docusaurus broken link fix

- backend/streetdrop-api/src/test/java/unit/annotation/WithMockCustomAnonymousUserSecurityContextFactory.java
- backend/streetdrop-api/src/test/java/unit/item/service/ItemLikeServiceTest.java
- backend/streetdrop-api/src/test/java/unit/item/service/ItemServiceTest.java
- backend/streetdrop-api/src/test/java/unit/security/provider/IdfvUserDetailsServiceTest.java
- backend/streetdrop-api/src/test/java/unit/security/provider/SecurityUserDetailsTest.java
- backend/streetdrop-api/src/test/java/unit/user/controller/UserControllerTest.java
- backend/streetdrop-api/src/test/java/unit/user/service/UserServiceTest.java
> :bug: fix(api): fix api test case

- backend/streetdrop-api/src/main/java/com/depromeet/common/dto/InfiniteScrollMetaResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dao/ItemDao.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dto/response/ItemGroupResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemRepositoryImpl.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/QueryDslItemRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/dto/response/UserResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserItemService.java
- backend/streetdrop-common/src/main/java/com/depromeet/util/WeekUtil.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/276
- ItemLike Count를 위해서 ItemLike를 Fetch Join시 Inner Join이 되어 좋아요한 게시글만 보여지는 문제 해결
> :ambulance: hotfix(api): unliked items don't show up in the drop list

- backend/streetdrop-api/src/main/java/com/depromeet/external/redis/RedisConfig.java
- backend/streetdrop-api/src/main/resources/application-dev.yml
- backend/streetdrop-api/src/main/resources/application-prod.yml
> :wrench: config(redis): add redis cache config class

- docs/docs/software-requirement-specification/Intrduction.md
- docs/docs/software-requirement-specification/change-management-process.md
- docs/docs/software-requirement-specification/environment.md
- docs/docs/software-requirement-specification/ovearall-description.md
> :memo: docs(docs): add basic srs document

- backend/streetdrop-api/src/main/resources/application-dev.yml
- backend/streetdrop-api/src/main/resources/application-prod.yml
Resolve : https://github.com/depromeet/street-drop-server/issues/249
- 개발 환경에서는 Swagger 사용
- 실서비스 환경에서는 Swagger 사용안함
> 🐛 fix(api): fix api swagger prod environment disable

- README.md
- close : #298 
- [편하게 보기](https://github.com/depromeet/street-drop-server/tree/docs/readme)
> :memo: docs: reduce readme image size

- backend/streetdrop-api/src/main/java/com/depromeet/common/error/GlobalExceptionHandler.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/305
> :recycle: hotfix(api): add Method not support exception

- backend/streetdrop-api/build.gradle
- Resolve : https://github.com/depromeet/street-drop-server/issues/310
> :hammer: config(api): spring cloud version update - security issue

- backend/streetdrop-api/src/main/java/com/depromeet/test/delay/DelayTestFilter.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/307
- Resolve : https://github.com/depromeet/street-drop-server/issues/287
> :sparkles: feat(api): add filter for testing response time delays

- README.md
- Resolve : https://github.com/depromeet/street-drop-server/issues/324
> :memo: docs : fix readme badge

- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/user/controller/UserBlockController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/user/dto/UserBlockAllResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/user/dto/UserBlockResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/user/repository/UserBlockRepository.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/user/service/UserBlockService.java
- backend/streetdrop-admin/streetdrop-admin-web/src/App.js
- backend/streetdrop-admin/streetdrop-admin-web/src/api/domain/user/UserBlockApi.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/user/UserBlockPage.js
- backend/streetdrop-admin/streetdrop-admin-web/src/layout/common/Menu.js
- backend/streetdrop-admin/streetdrop-admin-web/src/setupProxy.js
- resolve: https://github.com/depromeet/street-drop-server/issues/338
> :sparkles: feat(admin): add User Block List Page

- infra/jenkins/docker-compose.yml
- Resolve : https://github.com/depromeet/street-drop-server/issues/339
> :sparkles: feat : add jenkins docker compose setup

- backend/streetdrop-admin/Dockerfile
- backend/streetdrop-admin/docker-compose.yml
- backend/streetdrop-admin/streetdrop-admin-server/Dockerfile
- backend/streetdrop-admin/streetdrop-admin-web-server/app.js
- Resolve : https://github.com/depromeet/street-drop-server/issues/337
> :sparkles: feat(admin): add docker-compose set up to admin

- docs/blog/2023-09-12-apple-music-api-token.md
> :memo: docs: fix blog slug duplicated

- backend/streetdrop-api/src/test/java/unit/domains/geo/controller/GeoControllerTest.java
- backend/streetdrop-api/src/test/java/unit/domains/geo/service/GeoServiceTest.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/352
> :white_check_mark: test(api): add test to geo controller and service

- backend/streetdrop-api/src/test/java/unit/domains/item/controller/ItemControllerTest.java
- backend/streetdrop-api/src/test/java/unit/domains/item/service/ItemLikeServiceTest.java
- backend/streetdrop-api/src/test/java/unit/domains/item/service/ItemServiceTest.java
- backend/streetdrop-api/src/test/java/unit/domains/user/controller/UserBlockControllerTest.java
- backend/streetdrop-api/src/test/java/unit/domains/user/controller/UserControllerTest.java
- backend/streetdrop-api/src/test/java/unit/domains/user/service/UserBlockServiceTest.java
- backend/streetdrop-api/src/test/java/unit/domains/user/service/UserServiceTest.java
- backend/streetdrop-api/src/test/java/unit/domains/village/controller/VillageItemControllerTest.java
- backend/streetdrop-api/src/test/java/unit/domains/village/service/VillageAreaServiceTest.java
- backend/streetdrop-api/src/test/java/unit/domains/village/service/VillageItemServiceTest.java
Resolve : https://github.com/depromeet/street-drop-server/issues/363
> :recycle: chore(api) : test dir fix

- backend/streetdrop-api/src/test/java/unit/domains/notification/controller/NotificationControllerTest.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/367
> :white_check_mark: test(api) : add notificationController test

- backend/streetdrop-api/src/test/java/unit/domains/item/controller/ItemClaimControllerTest.java
- backend/streetdrop-api/src/test/java/unit/domains/item/service/ItemClaimServiceTest.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/366
> :white_check_mark: test(api) : add item claim and service test

- backend/streetdrop-admin/streetdrop-admin-server/build.gradle
- backend/streetdrop-api/build.gradle
- backend/streetdrop-batch/build.gradle
- backend/streetdrop-notification/build.gradle
- backend/streetdrop-search/build.gradle
- Resolve : https://github.com/depromeet/street-drop-server/issues/360
> :wrench: config(all) : gradle setup not create plain jar

- README.md
Resolve : https://github.com/depromeet/street-drop-server/issues/329
> :memo: docs: update readme add link to docs and new architecture

- backend/streetdrop-api/src/main/java/com/depromeet/domains/geo/controller/GeoController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/controller/ItemClaimController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/controller/ItemController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/controller/ItemLikeController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/notification/controller/NotificationController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserBlockController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserItemController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/village/controller/VillageItemController.java
- backend/streetdrop-search/src/main/java/com/depromeet/apis/MusicController.java
> :sparkles: feat(api, search): add emoji on swagger docs

- .github/workflows/pull_request_template.md
> :wrench: config: create pull request template

- backend/streetdrop-admin/streetdrop-admin-server/build.gradle
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/controller/ItemController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/controller/ItemService.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/ItemDetailResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/detail/ItemBasicInfoDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/detail/ItemLocationInfoDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/detail/ItemMusicInfoDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/detail/ItemUserInfoDto.java
- backend/streetdrop-admin/streetdrop-admin-web/src/api/domain/item/ItemApi.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/items/ItemDetailPage.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/items/ItemListPage.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/user/UserListPage.js
- Resolve : https://github.com/depromeet/street-drop-server/issues/233
> :sparkles: feat(admin): add item detail page and item delete refactoring

- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/user/service/UserBlockService.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/379
> :bug: fix(admin): fix blocked user appears to be a blocker user

- backend/streetdrop-api/src/main/java/com/depromeet/domains/geo/controller/GeoController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserItemController.java
> :sparkles: feat(api): Add ApiResponse, ApiErrorReponse Annotation

- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/dto/request/NicknameChangeDto.java
- backend/streetdrop-api/src/test/java/unit/domains/user/controller/UserControllerTest.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/364
> :bug: fix(api): nickname size checking bug fix

- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/event/CreateSongGenreEvent.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/genre/handler/SongGenreEventHandler.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/genre/handler/SongGenreHandler.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/genre/repository/GenreRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/genre/repository/SongGenreRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/genre/service/GenreService.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/genre/service/SongGenreService.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/music/service/MusicService.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/227
> :bug: fix(api): solving the problem of saving the song null

- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dto/response/ItemDetailResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemService.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/400
> :ambulance: hotfix: add user response to musicApp

- backend/streetdrop-api/src/main/java/com/depromeet/external/redis/RedisConfig.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/398
> :bug: fix: remove configuration

- backend/streetdrop-api/src/main/resources/db/migration/V20231103_add_index_to_item_like.sql
- backend/streetdrop-domain/src/main/java/com/depromeet/item/ItemLike.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/395
> :sparkles: feat: add index to item_like

- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/dao/UserItemLikeDao.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemLikeRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/ItemLikeRepositoryImpl.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/repository/QueryDslItemLikeRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemLikeService.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserItemService.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/392
```
Hibernate: select i1_0.item_like_id,i1_0.created_at,i2_0.item_id,a1_0.album_cover_id,a1_0.album_image,a1_0.album_thumbnail,i2_0.content,i2_0.created_at,i3_0.item_location_id,i3_0.created_at,i3_0.item_id,i3_0.modified_at,i3_0.name,i3_0.point,i3_0.village_id,i2_0.modified_at,s1_0.song_id,a2_0.album_id,a2_0.album_cover_id,a2_0.artist_id,a2_0.name,s1_0.name,i2_0.user_id,i1_0.modified_at,i1_0.user_id from item_like i1_0 join item i2_0 on i2_0.item_id=i1_0.item_id join item_location i3_0 on i2_0.item_id=i3_0.item_id join album_cover a1_0 on a1_0.album_cover_id=i2_0.album_cover_id join song s1_0 on s1_0.song_id=i2_0.song_id join album a2_0 on a2_0.album_id=s1_0.album_id where i1_0.user_id=? and i1_0.item_like_id<? order …
```
> :bug: fix: ItemLikeRepository Query refactoring to queryDSL

- backend/streetdrop-api/src/main/resources/application.yml
- Resolve : https://github.com/depromeet/street-drop-server/issues/408
- About Http Gzip Compression
- https://developer.mozilla.org/ko/docs/Web/HTTP/Compression
> :hammer: config: gzip setup to config file

- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/controller/ItemClaimController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/ItemClaimAllResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/ItemClaimRequestDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/dto/ItemClaimResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/repository/ItemClaimRepository.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/item/service/ItemClaimService.java
- backend/streetdrop-admin/streetdrop-admin-web/src/api/domain/item/ItemClaimApi.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/items/ItemReportPage.js
- 어드민 신고 관리 페이지
- 어드민 신고 후 처리 상태 변경 가능
> :sparkles: feat: add admin report view

- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/recommend/search/controller/SearchRecommendController.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/recommend/search/dto/SearchRecommendAllResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/recommend/search/dto/SearchRecommendResponseDto.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/recommend/search/repository/SearchRecommendTermRepository.java
- backend/streetdrop-admin/streetdrop-admin-server/src/main/java/com/depromeet/domains/recommend/search/service/SearchRecommendService.java
- backend/streetdrop-admin/streetdrop-admin-web/src/api/domain/music/RecommendApi.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/items/music/recommend/MusicRecommend.js
> :sparkles: feat: add admin music recommend view

- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/dto/response/UserDistanceResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
- backend/streetdrop-api/src/main/resources/db/migration/V20240206__add_distance_to_users_level.sql
- backend/streetdrop-domain/src/main/java/com/depromeet/user/UserLevel.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/433
> :sparkles: feat: add user distance api

- backend/streetdrop-admin/streetdrop-admin-web/src/api/domain/music/RecommendApi.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/items/music/recommend/MusicRecommend.js
- backend/streetdrop-admin/streetdrop-admin-web/src/components/items/music/recommend/MusicRecommendEventCreate.js
> :sparkles: feat: add music recommend create view

- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/controller/PopupController.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/data/GuidePopupData.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/data/LevelUpPopupData.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/dto/request/PopupReadRequestDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/dto/response/PopupDataDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/dto/response/PopupResponseDto.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/dto/response/popupcontent/GuidePopupContent.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/dto/response/popupcontent/LevelUpPopupContent.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/dto/response/popupcontent/PopupContent.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/error/PopupErrorCode.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/repository/PopupRepository.java
- backend/streetdrop-api/src/main/java/com/depromeet/domains/popup/service/PopupService.java
- backend/streetdrop-api/src/main/java/com/depromeet/security/config/WebSecurityConfig.java
- backend/streetdrop-api/src/main/resources/db/migration/V20240305__add_popup_table.sql
- backend/streetdrop-batch/src/main/java/com/depromeet/domains/popup/repository/PopupRepository.java
- backend/streetdrop-batch/src/main/java/com/depromeet/domains/popup/service/PopupService.java
- backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
- backend/streetdrop-domain/src/main/java/com/depromeet/popup/Popup.java
- Resolve : https://github.com/depromeet/street-drop-server/issues/441
> :sparkles: feat: add popup feature

- .github/workflows/flyway-naming-check.yml
- Resolve : https://github.com/depromeet/street-drop-server/issues/460
> :hammer: config: add flyway naming check

- backend/streetdrop-search/src/main/java/com/depromeet/music/service/AppleMusicService.java
> :recycle: refactor(search): change apple music search limit 10 -> 20

- backend/settings.gradle
> :bug: fix: gradle in notification module does not disappear
